languageCode = 'en-us'
title = 'Tin Radio Archive'
theme = [
    'hugo-shortcode-roneo-collection', # Audio player
    'hugo-PaperMod'
]

[params]
env = 'production'

mainSections = ['posts']
disableSpecial1stPost = true
defaultTheme = 'light'

ShowPostNavLinks = true

[taxonomies]
tag = 'tags'
season = 'seasons'

[markup.goldmark.renderer]
unsafe = true